### ISSUE TITLE
git grep -I is not used still

### ISSUE THREAD

**Issue by andreymolchanov** [gollum/grit_adapter#12]
Hello, 

I use the latest Gollum version. It searches all files including css, templates and so on desipte this https://github.com/gollum/grit_adapter/pull/2 . Is there any solution?

**Comment by dometto** [comment]
Not sure. Could it be that the behavior of git grep has changed in recent versions?

On 19 nov. 2015, at 17:17, "Andrey Molchanov" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,

I use the latest Gollum version. It searches all files including css, templates and so on desipte this #2<https://github.com/gollum/grit_adapter/pull/2> . Is there any solution?

**Comment by bartkamphorst** [comment]
Related to https://github.com/gollum/gollum/issues/1085 .

**Comment by bartkamphorst** [comment]
According to [the docs](https://git-scm.com/docs/git-grep) the `-I` flag is (still) the one we need. So it seems that either the flag is not passed correctly to the git binary or the `.gitattributes` file is not found / not used.

**Comment by andreymolchanov** [comment]
When I execute git command from the console, it works right.
It seems that -I flag is not passed.
What would you advise?

**Comment by bartkamphorst** [comment]
Thanks for following up. How do you call it from the console?

**Comment by bartkamphorst** [comment]
@andreymolchanov See also issue https://github.com/gollum/gollum/issues/1085 . I might have a quick fix with https://github.com/gollum/grit_adapter/pull/13, perhaps you could try this out?

**Comment by andreymolchanov** [comment]
I call <code>git grep -I "q"</code> from console and it works. When I call <code>git grep "q"</code> it shows excess results. So I consider gollum not using -I attribute.

**Comment by bartkamphorst** [comment]
Yes, you are right that it is not being used, see my previous comment for the cause and the fix. It would be great if you could try out that branch!

**Comment by andreymolchanov** [comment]
We tried it and it hasn't help.
<git grep -I -i -c "css" "HEAD" --> executed from the console returns correct results.
It seems, that there is a difference between git in the console and git used by grit_adapter. Is it possible?

**Comment by andreymolchanov** [comment]
Hello,
The issue is still not solved, could you please reopen it?

**Comment by bartkamphorst** [comment]
It should be fixed in `master`.
